version: "3.0"
services:
  mongo:
    image: mongo
    ports:
      - 5984:5984
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - ./data:/opt/couchdb/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  node: 
    image: node
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=4321
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
      - 4321:4321
    command: "npm start"
    environment:
      MONGO_TRIBES_URI: mongodb://mongo:5984/tribes